### ISSUE TITLE
NullPointerException in WavefrontMetricsProcessor.processGauge

### ISSUE THREAD

**Issue by panghy** [wavefrontHQ/java-lib#66]
```
WARN  [2020-09-30 06:27:25,857] com.wavefront.integrations.metrics.WavefrontYammerHttpMetricsReporter: Unable to process entry and pass to the metrics processor
! java.lang.NullPointerException: null
! at com.wavefront.integrations.metrics.WavefrontMetricsProcessor.processGauge(WavefrontMetricsProcessor.java:231)
! at com.wavefront.integrations.metrics.HttpMetricsProcessor.processGauge(HttpMetricsProcessor.java:33)
! at com.wavefront.integrations.metrics.WavefrontMetricsProcessor.processGauge(WavefrontMetricsProcessor.java:28)
! at com.yammer.metrics.core.Gauge.processWith(Gauge.java:28)
! at com.wavefront.integrations.metrics.WavefrontYammerHttpMetricsReporter.processEntry(WavefrontYammerHttpMetricsReporter.java:342)
! at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
! at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
! at java.base/java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet.lambda$entryConsumer$0(Collections.java:1593)
! at java.base/java.util.concurrent.ConcurrentHashMap$EntrySpliterator.forEachRemaining(ConcurrentHashMap.java:3652)
! at java.base/java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet$UnmodifiableEntrySetSpliterator.forEachRemaining(Collections.java:1618)
! at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
! at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
! at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
! at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
! at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
! at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
! at com.wavefront.integrations.metrics.WavefrontYammerHttpMetricsReporter.run(WavefrontYammerHttpMetricsReporter.java:323)
! at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
! at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
! at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
! at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
! at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
! at java.base/java.lang.Thread.run(Thread.java:832)

```

**Comment by basilisk487** [comment]
Fixed in PR #68
